// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60sl5Hoi442wOs3MOfi4KnoqeucOnimw',
    appId: '1:684495506243:web:0426fd047478db2392bdf6',
    messagingSenderId: '684495506243',
    projectId: 'edu-vista-73d0b',
    authDomain: 'edu-vista-73d0b.firebaseapp.com',
    storageBucket: 'edu-vista-73d0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnA4oaFGeTFplHnL4bQhoJoTYkGKMMGtA',
    appId: '1:684495506243:android:4c97c5f900dbe2a192bdf6',
    messagingSenderId: '684495506243',
    projectId: 'edu-vista-73d0b',
    storageBucket: 'edu-vista-73d0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2v4UXYxFS3wQIFAckFrtHcaGX08ApEO8',
    appId: '1:684495506243:ios:0bf15f6973aab47e92bdf6',
    messagingSenderId: '684495506243',
    projectId: 'edu-vista-73d0b',
    storageBucket: 'edu-vista-73d0b.appspot.com',
    iosBundleId: 'com.example.eduVista',
  );
}
